server:
  port: 8081

springfox:
  documentation:
    auto-startup: false

spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:9092}

pscs:
  delta:
    group-id: psc-delta-consumer
    topic: ${PSC_DELTA_TOPIC:psc-delta}
    retry-attempts: ${PSC_DELTA_ATTEMPTS:4}
    backoff-delay: ${PSC_DELTA_BACKOFF_DELAY:100}

api:
  psc-data-api-key: ${PSC_DATA_API_KEY:localhost}
  api-url: ${API_URL:http://localhost:8888}
  internal-api-url: ${INTERNAL_API_URL:localhost}


logger:
  namespace: psc-delta-consumer
