package uk.gov.companieshouse.psc.delta.mapper;

import static java.util.Map.entry;
import static uk.gov.companieshouse.psc.delta.PscDeltaConsumerApplication.NAMESPACE;

import consumer.exception.NonRetryableErrorException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Base64;
import java.util.Locale;
import java.util.Map;
import org.apache.commons.codec.digest.DigestUtils;
import uk.gov.companieshouse.logging.Logger;
import uk.gov.companieshouse.logging.LoggerFactory;
import uk.gov.companieshouse.psc.delta.logging.DataMapHolder;

public final class MapperUtils {

    private static final Logger LOGGER = LoggerFactory.getLogger(NAMESPACE);
    private static final String TIME_START_OF_DAY = "000000";
    private static final String DATETIME_PATTERN = "yyyyMMddHHmmss";
    private static final DateTimeFormatter UTC_DATETIME_FORMATTER =
            DateTimeFormatter.ofPattern(DATETIME_PATTERN, Locale.UK).withZone(ZoneId.of("UTC"));

    // Define constants for frequently used substrings
    private static final String AS_CONTROL_OVER_FIRM = "-as-control-over-firm";
    private static final String AS_CONTROL_OVER_TRUST = "-as-control-over-trust";
    private static final String AS_FIRM = "-as-firm";
    private static final String AS_NOMINEE = "-as-nominee";
    private static final String AS_NOMINEE_PERSON = AS_NOMINEE + "-person";
    private static final String AS_NOMINEE_ANOTHER_ENTITY = AS_NOMINEE + "-another-entity";
    private static final String AS_TRUST = "-as-trust";
    private static final String ENGLAND_WALES = "-england-wales";
    private static final String LIMITED_LIABILITY_PARTNERSHIP = "-limited-liability-partnership";
    private static final String MORE_THAN_25_PERCENT = "-more-than-25-percent";
    private static final String NORTHERN_IRELAND = "-northern-ireland";
    private static final String OWNERSHIP_OF_SHARES = "ownership-of-shares";
    private static final String PART_RIGHT_TO_SHARE_SURPLUS_ASSETS = "part-right-to-share-surplus-assets";
    private static final String PERCENT_25_TO_50 = "-25-to-50-percent";
    private static final String PERCENT_50_TO_75 = "-50-to-75-percent";
    private static final String PERCENT_75_TO_100 = "-75-to-100-percent";
    private static final String REGISTERED_OVERSEAS_ENTITY = "-registered-overseas-entity";
    private static final String REGISTERED_OWNER = "registered-owner";
    private static final String RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS = "right-to-appoint-and-remove-directors";
    private static final String RIGHT_TO_APPOINT_AND_REMOVE_MEMBERS = "right-to-appoint-and-remove-members";
    private static final String RIGHT_TO_SHARE_SURPLUS_ASSETS = "right-to-share-surplus-assets";
    private static final String SCOTLAND = "-scotland";
    private static final String SIGNIFICANT_INFLUENCE_CONTROL = "significant-influence-or-control";
    private static final String VOTING_RIGHTS = "voting-rights";
    private static final String RIGHT_TO_APPOINT_AND_REMOVE_PERSON = "right-to-appoint-and-remove-person";

    private MapperUtils() {
    }

    /**
     * Parse a date string (expected format: DATE_PATTERN). Implementation note: Instant conversion requires input level of detail
     * is Seconds, so TIME_START_OF_DAY is appended before conversion.
     *
     * @param rawDateString the date string
     * @return the LocalDate corresponding to the parsed string (at UTC by definition)
     * @throws NonRetryableErrorException if date parsing fails
     */
    public static LocalDate parseLocalDate(final String rawDateString)
            throws NonRetryableErrorException {
        return convertToLocalDate(rawDateString + TIME_START_OF_DAY);
    }

    private static LocalDate convertToLocalDate(final String date) {
        try {
            return LocalDate.parse(date, UTC_DATETIME_FORMATTER);
        } catch (final DateTimeParseException exception) {
            final String msg = "Failed to parse date/time: [%s]".formatted(date);
            LOGGER.error(msg, DataMapHolder.getLogMap());
            throw new NonRetryableErrorException(msg, exception);
        }
    }

    /**
     * encode the String passed in for use in links and ids.
     */
    public static String encode(final String unencodedString) {
        final String salt = "ks734s_sdgOc4£b2";
        return Base64.getUrlEncoder().withoutPadding().encodeToString(
                DigestUtils.sha1(unencodedString + salt));
    }

    /**
     * Create a hashmap for natures of control.
     */
    public static Map<String, String> getNaturesOfControlMap(final String companyNumber) {
        if (companyNumber.length() < 2) {
            return getNaturesOfControlMap();
        } else {
            final String typeCode = companyNumber.substring(0, 2);
            if (typeCode.equals("SO") || typeCode.equals("NC") || typeCode.equals("OC")) {
                return getLlpNaturesOfControlMap();
            } else if (typeCode.equals("OE")) {
                return getRoeNaturesOfControlMap();
            } else {
                return getNaturesOfControlMap();
            }
        }
    }

    /**
     * Create a hashmap for natures of control.
     */
    private static Map<String, String> getNaturesOfControlMap() {
        return Map.<String, String>ofEntries( // explicitly specify Map types to avoid compilation and analysis slowdown for large argument lists
            entry("OWNERSHIPOFSHARES_25TO50PERCENT_AS_PERSON", OWNERSHIP_OF_SHARES + PERCENT_25_TO_50),
            entry("OWNERSHIPOFSHARES_50TO75PERCENT_AS_PERSON", OWNERSHIP_OF_SHARES + PERCENT_50_TO_75),
            entry("OWNERSHIPOFSHARES_75TO100PERCENT_AS_PERSON", OWNERSHIP_OF_SHARES + PERCENT_75_TO_100),
            entry("OWNERSHIPOFSHARES_25TO50PERCENT_AS_TRUST", OWNERSHIP_OF_SHARES + PERCENT_25_TO_50 + AS_TRUST),
            entry("OWNERSHIPOFSHARES_50TO75PERCENT_AS_TRUST", OWNERSHIP_OF_SHARES + PERCENT_50_TO_75 + AS_TRUST),
            entry("OWNERSHIPOFSHARES_75TO100PERCENT_AS_TRUST", OWNERSHIP_OF_SHARES + PERCENT_75_TO_100 + AS_TRUST),
            entry("OWNERSHIPOFSHARES_25TO50PERCENT_AS_FIRM", OWNERSHIP_OF_SHARES + PERCENT_25_TO_50 + AS_FIRM),
            entry("OWNERSHIPOFSHARES_50TO75PERCENT_AS_FIRM", OWNERSHIP_OF_SHARES + PERCENT_50_TO_75 + AS_FIRM),
            entry("OWNERSHIPOFSHARES_75TO100PERCENT_AS_FIRM", OWNERSHIP_OF_SHARES + PERCENT_75_TO_100 + AS_FIRM),
            entry("VOTINGRIGHTS_25TO50PERCENT_AS_PERSON", VOTING_RIGHTS + PERCENT_25_TO_50),
            entry("VOTINGRIGHTS_50TO75PERCENT_AS_PERSON", VOTING_RIGHTS + PERCENT_50_TO_75),
            entry("VOTINGRIGHTS_75TO100PERCENT_AS_PERSON", VOTING_RIGHTS + PERCENT_75_TO_100),
            entry("VOTINGRIGHTS_25TO50PERCENT_AS_TRUST", VOTING_RIGHTS + PERCENT_25_TO_50 + AS_TRUST),
            entry("VOTINGRIGHTS_50TO75PERCENT_AS_TRUST", VOTING_RIGHTS + PERCENT_50_TO_75 + AS_TRUST),
            entry("VOTINGRIGHTS_75TO100PERCENT_AS_TRUST", VOTING_RIGHTS + PERCENT_75_TO_100 + AS_TRUST),
            entry("VOTINGRIGHTS_25TO50PERCENT_AS_FIRM", VOTING_RIGHTS + PERCENT_25_TO_50 + AS_FIRM),
            entry("VOTINGRIGHTS_50TO75PERCENT_AS_FIRM", VOTING_RIGHTS + PERCENT_50_TO_75 + AS_FIRM),
            entry("VOTINGRIGHTS_75TO100PERCENT_AS_FIRM", VOTING_RIGHTS + PERCENT_75_TO_100 + AS_FIRM),
            entry("RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_PERSON", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS),
            entry("RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_TRUST", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS + AS_TRUST),
            entry("RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_FIRM", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS + AS_FIRM),
            entry("SIGINFLUENCECONTROL_AS_PERSON", SIGNIFICANT_INFLUENCE_CONTROL),
            entry("SIGINFLUENCECONTROL_AS_TRUST", SIGNIFICANT_INFLUENCE_CONTROL + AS_TRUST),
            entry("SIGINFLUENCECONTROL_AS_FIRM", SIGNIFICANT_INFLUENCE_CONTROL + AS_FIRM),
            entry("PART_RIGHTTOSHARESURPLUSASSETS_25TO50PERCENT_AS_PERSON", PART_RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_25_TO_50),
            entry("PART_RIGHTTOSHARESURPLUSASSETS_50TO75PERCENT_AS_PERSON", PART_RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_50_TO_75),
            entry("PART_RIGHTTOSHARESURPLUSASSETS_75TO100PERCENT_AS_PERSON", PART_RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_75_TO_100),
            entry("PART_RIGHTTOSHARESURPLUSASSETS_25TO50PERCENT_AS_TRUST", PART_RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_25_TO_50 + AS_TRUST),
            entry("PART_RIGHTTOSHARESURPLUSASSETS_50TO75PERCENT_AS_TRUST", PART_RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_50_TO_75 + AS_TRUST),
            entry("PART_RIGHTTOSHARESURPLUSASSETS_75TO100PERCENT_AS_TRUST", PART_RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_75_TO_100 + AS_TRUST),
            entry("PART_RIGHTTOSHARESURPLUSASSETS_25TO50PERCENT_AS_FIRM", PART_RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_25_TO_50 + AS_FIRM),
            entry("PART_RIGHTTOSHARESURPLUSASSETS_50TO75PERCENT_AS_FIRM", PART_RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_50_TO_75 + AS_FIRM),
            entry("PART_RIGHTTOSHARESURPLUSASSETS_75TO100PERCENT_AS_FIRM", PART_RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_75_TO_100 + AS_FIRM),
            entry("RIGHTTOAPPOINTANDREMOVEPERSONS_AS_PERSON", RIGHT_TO_APPOINT_AND_REMOVE_PERSON),
            entry("RIGHTTOAPPOINTANDREMOVEPERSONS_AS_FIRM", RIGHT_TO_APPOINT_AND_REMOVE_PERSON + AS_FIRM),
            entry("RIGHTTOAPPOINTANDREMOVEPERSONS_AS_TRUST", RIGHT_TO_APPOINT_AND_REMOVE_PERSON + AS_TRUST),
            entry("OE_OWNERSHIPOFSHARES_MORETHAN25PERCENT_AS_PERSON", OWNERSHIP_OF_SHARES + MORE_THAN_25_PERCENT + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_OWNERSHIPOFSHARES_MORETHAN25PERCENT_AS_TRUST", OWNERSHIP_OF_SHARES + MORE_THAN_25_PERCENT + AS_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_OWNERSHIPOFSHARES_MORETHAN25PERCENT_AS_FIRM", OWNERSHIP_OF_SHARES + MORE_THAN_25_PERCENT + AS_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_VOTINGRIGHTS_MORETHAN25PERCENT_AS_PERSON", VOTING_RIGHTS + MORE_THAN_25_PERCENT + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_VOTINGRIGHTS_MORETHAN25PERCENT_AS_TRUST", VOTING_RIGHTS + MORE_THAN_25_PERCENT + AS_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_VOTINGRIGHTS_MORETHAN25PERCENT_AS_FIRM", VOTING_RIGHTS + MORE_THAN_25_PERCENT + AS_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_PERSON", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_TRUST", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS + AS_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_FIRM", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS + AS_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_SIGINFLUENCECONTROL_AS_PERSON", SIGNIFICANT_INFLUENCE_CONTROL + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_SIGINFLUENCECONTROL_AS_TRUST", SIGNIFICANT_INFLUENCE_CONTROL + AS_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_SIGINFLUENCECONTROL_AS_FIRM", SIGNIFICANT_INFLUENCE_CONTROL + AS_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("RIGHTTOSHARESURPLUSASSETS_25TO50PERCENT_AS_PERSON", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_25_TO_50 + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_50TO75PERCENT_AS_PERSON", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_50_TO_75 + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_75TO100PERCENT_AS_PERSON", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_75_TO_100 + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_25TO50PERCENT_AS_TRUST", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_25_TO_50 + AS_TRUST + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_50TO75PERCENT_AS_TRUST", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_50_TO_75 + AS_TRUST + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_75TO100PERCENT_AS_TRUST", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_75_TO_100 + AS_TRUST + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_25TO50PERCENT_AS_FIRM", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_25_TO_50 + AS_FIRM + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_50TO75PERCENT_AS_FIRM", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_50_TO_75 + AS_FIRM + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_75TO100PERCENT_AS_FIRM", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_75_TO_100 + AS_FIRM + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOAPPOINTANDREMOVEMEMBERS_AS_PERSON", RIGHT_TO_APPOINT_AND_REMOVE_MEMBERS + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOAPPOINTANDREMOVEMEMBERS_AS_FIRM", RIGHT_TO_APPOINT_AND_REMOVE_MEMBERS + AS_FIRM + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOAPPOINTANDREMOVEMEMBERS_AS_TRUST", RIGHT_TO_APPOINT_AND_REMOVE_MEMBERS + AS_TRUST + LIMITED_LIABILITY_PARTNERSHIP),
            entry("OE_OWNERSHIPOFSHARES_MORETHAN25PERCENT_AS_CONTROLOVERTRUST", OWNERSHIP_OF_SHARES + MORE_THAN_25_PERCENT + AS_CONTROL_OVER_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_VOTINGRIGHTS_MORETHAN25PERCENT_AS_CONTROLOVERTRUST", VOTING_RIGHTS + MORE_THAN_25_PERCENT + AS_CONTROL_OVER_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_CONTROLOVERTRUST", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS + AS_CONTROL_OVER_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_SIGINFLUENCECONTROL_AS_CONTROLOVERTRUST", SIGNIFICANT_INFLUENCE_CONTROL + AS_CONTROL_OVER_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_OWNERSHIPOFSHARES_MORETHAN25PERCENT_AS_CONTROLOVERFIRM", OWNERSHIP_OF_SHARES + MORE_THAN_25_PERCENT + AS_CONTROL_OVER_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_VOTINGRIGHTS_MORETHAN25PERCENT_AS_CONTROLOVERFIRM", VOTING_RIGHTS + MORE_THAN_25_PERCENT + AS_CONTROL_OVER_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_CONTROLOVERFIRM", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS + AS_CONTROL_OVER_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_SIGINFLUENCECONTROL_AS_CONTROLOVERFIRM", SIGNIFICANT_INFLUENCE_CONTROL + AS_CONTROL_OVER_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_REGOWNER_AS_NOMINEEPERSON_ENGLANDWALES", REGISTERED_OWNER + AS_NOMINEE_PERSON + ENGLAND_WALES + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_REGOWNER_AS_NOMINEEPERSON_SCOTLAND", REGISTERED_OWNER + AS_NOMINEE_PERSON + SCOTLAND + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_REGOWNER_AS_NOMINEEPERSON_NORTHERNIRELAND", REGISTERED_OWNER + AS_NOMINEE_PERSON + NORTHERN_IRELAND + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_REGOWNER_AS_NOMINEEANOTHERENTITY_ENGLANDWALES", REGISTERED_OWNER + AS_NOMINEE_ANOTHER_ENTITY + ENGLAND_WALES + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_REGOWNER_AS_NOMINEEANOTHERENTITY_SCOTLAND", REGISTERED_OWNER + AS_NOMINEE_ANOTHER_ENTITY + SCOTLAND + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_REGOWNER_AS_NOMINEEANOTHERENTITY_NORTHERNIRELAND", REGISTERED_OWNER + AS_NOMINEE_ANOTHER_ENTITY + NORTHERN_IRELAND + REGISTERED_OVERSEAS_ENTITY)
        );
    }

    /**
     * Create a hashmap for natures of control llps.
     */
    public static Map<String, String> getLlpNaturesOfControlMap() {
        return Map.ofEntries(
            entry("RIGHTTOSHARESURPLUSASSETS_25TO50PERCENT_AS_PERSON", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_25_TO_50 + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_50TO75PERCENT_AS_PERSON", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_50_TO_75 + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_75TO100PERCENT_AS_PERSON", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_75_TO_100 + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_25TO50PERCENT_AS_TRUST", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_25_TO_50 + AS_TRUST + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_50TO75PERCENT_AS_TRUST", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_50_TO_75 + AS_TRUST + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_75TO100PERCENT_AS_TRUST", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_75_TO_100 + AS_TRUST + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_25TO50PERCENT_AS_FIRM", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_25_TO_50 + AS_FIRM + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_50TO75PERCENT_AS_FIRM", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_50_TO_75 + AS_FIRM + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOSHARESURPLUSASSETS_75TO100PERCENT_AS_FIRM", RIGHT_TO_SHARE_SURPLUS_ASSETS + PERCENT_75_TO_100 + AS_FIRM + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOAPPOINTANDREMOVEMEMBERS_AS_PERSON", RIGHT_TO_APPOINT_AND_REMOVE_MEMBERS + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOAPPOINTANDREMOVEMEMBERS_AS_FIRM", RIGHT_TO_APPOINT_AND_REMOVE_MEMBERS + AS_FIRM + LIMITED_LIABILITY_PARTNERSHIP),
            entry("RIGHTTOAPPOINTANDREMOVEMEMBERS_AS_TRUST", RIGHT_TO_APPOINT_AND_REMOVE_MEMBERS + AS_TRUST + LIMITED_LIABILITY_PARTNERSHIP),
            entry("VOTINGRIGHTS_25TO50PERCENT_AS_PERSON", VOTING_RIGHTS + PERCENT_25_TO_50 + LIMITED_LIABILITY_PARTNERSHIP),
            entry("VOTINGRIGHTS_50TO75PERCENT_AS_PERSON", VOTING_RIGHTS + PERCENT_50_TO_75 + LIMITED_LIABILITY_PARTNERSHIP),
            entry("VOTINGRIGHTS_75TO100PERCENT_AS_PERSON", VOTING_RIGHTS + PERCENT_75_TO_100 + LIMITED_LIABILITY_PARTNERSHIP),
            entry("VOTINGRIGHTS_25TO50PERCENT_AS_TRUST", VOTING_RIGHTS + PERCENT_25_TO_50 + AS_TRUST + LIMITED_LIABILITY_PARTNERSHIP),
            entry("VOTINGRIGHTS_50TO75PERCENT_AS_TRUST", VOTING_RIGHTS + PERCENT_50_TO_75 + AS_TRUST + LIMITED_LIABILITY_PARTNERSHIP),
            entry("VOTINGRIGHTS_75TO100PERCENT_AS_TRUST", VOTING_RIGHTS + PERCENT_75_TO_100 + AS_TRUST + LIMITED_LIABILITY_PARTNERSHIP),
            entry("VOTINGRIGHTS_25TO50PERCENT_AS_FIRM", VOTING_RIGHTS + PERCENT_25_TO_50 + AS_FIRM + LIMITED_LIABILITY_PARTNERSHIP),
            entry("VOTINGRIGHTS_50TO75PERCENT_AS_FIRM", VOTING_RIGHTS + PERCENT_50_TO_75 + AS_FIRM + LIMITED_LIABILITY_PARTNERSHIP),
            entry("VOTINGRIGHTS_75TO100PERCENT_AS_FIRM", VOTING_RIGHTS + PERCENT_75_TO_100 + AS_FIRM + LIMITED_LIABILITY_PARTNERSHIP),
            entry("SIGINFLUENCECONTROL_AS_PERSON", SIGNIFICANT_INFLUENCE_CONTROL + LIMITED_LIABILITY_PARTNERSHIP),
            entry("SIGINFLUENCECONTROL_AS_TRUST", SIGNIFICANT_INFLUENCE_CONTROL + AS_TRUST + LIMITED_LIABILITY_PARTNERSHIP),
            entry("SIGINFLUENCECONTROL_AS_FIRM", SIGNIFICANT_INFLUENCE_CONTROL + AS_FIRM + LIMITED_LIABILITY_PARTNERSHIP)
        );
    }

    /**
     * Create a hashmap for natures of control ROEs.
     */
    private static Map<String, String> getRoeNaturesOfControlMap() {
        return Map.ofEntries(
            entry("OE_OWNERSHIPOFSHARES_MORETHAN25PERCENT_AS_PERSON", OWNERSHIP_OF_SHARES + MORE_THAN_25_PERCENT + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_OWNERSHIPOFSHARES_MORETHAN25PERCENT_AS_TRUST", OWNERSHIP_OF_SHARES + MORE_THAN_25_PERCENT + AS_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_OWNERSHIPOFSHARES_MORETHAN25PERCENT_AS_FIRM", OWNERSHIP_OF_SHARES + MORE_THAN_25_PERCENT + AS_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_VOTINGRIGHTS_MORETHAN25PERCENT_AS_PERSON", VOTING_RIGHTS + MORE_THAN_25_PERCENT + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_VOTINGRIGHTS_MORETHAN25PERCENT_AS_TRUST", VOTING_RIGHTS + MORE_THAN_25_PERCENT + AS_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_VOTINGRIGHTS_MORETHAN25PERCENT_AS_FIRM", VOTING_RIGHTS + MORE_THAN_25_PERCENT + AS_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_PERSON", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_TRUST", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS + AS_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_FIRM", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS + AS_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_SIGINFLUENCECONTROL_AS_PERSON", SIGNIFICANT_INFLUENCE_CONTROL + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_SIGINFLUENCECONTROL_AS_TRUST", SIGNIFICANT_INFLUENCE_CONTROL + AS_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_SIGINFLUENCECONTROL_AS_FIRM", SIGNIFICANT_INFLUENCE_CONTROL + AS_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_OWNERSHIPOFSHARES_MORETHAN25PERCENT_AS_CONTROLOVERTRUST", OWNERSHIP_OF_SHARES + MORE_THAN_25_PERCENT + AS_CONTROL_OVER_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_VOTINGRIGHTS_MORETHAN25PERCENT_AS_CONTROLOVERTRUST", VOTING_RIGHTS + MORE_THAN_25_PERCENT + AS_CONTROL_OVER_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_CONTROLOVERTRUST", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS + AS_CONTROL_OVER_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_SIGINFLUENCECONTROL_AS_CONTROLOVERTRUST", SIGNIFICANT_INFLUENCE_CONTROL + AS_CONTROL_OVER_TRUST + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_OWNERSHIPOFSHARES_MORETHAN25PERCENT_AS_CONTROLOVERFIRM", OWNERSHIP_OF_SHARES + MORE_THAN_25_PERCENT + AS_CONTROL_OVER_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_VOTINGRIGHTS_MORETHAN25PERCENT_AS_CONTROLOVERFIRM", VOTING_RIGHTS + MORE_THAN_25_PERCENT + AS_CONTROL_OVER_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_RIGHTTOAPPOINTANDREMOVEDIRECTORS_AS_CONTROLOVERFIRM", RIGHT_TO_APPOINT_AND_REMOVE_DIRECTORS + AS_CONTROL_OVER_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_SIGINFLUENCECONTROL_AS_CONTROLOVERFIRM", SIGNIFICANT_INFLUENCE_CONTROL + AS_CONTROL_OVER_FIRM + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_REGOWNER_AS_NOMINEEPERSON_ENGLANDWALES", REGISTERED_OWNER + AS_NOMINEE_PERSON + ENGLAND_WALES + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_REGOWNER_AS_NOMINEEPERSON_SCOTLAND", REGISTERED_OWNER + AS_NOMINEE_PERSON + SCOTLAND + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_REGOWNER_AS_NOMINEEPERSON_NORTHERNIRELAND", REGISTERED_OWNER + AS_NOMINEE_PERSON + NORTHERN_IRELAND + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_REGOWNER_AS_NOMINEEANOTHERENTITY_ENGLANDWALES", REGISTERED_OWNER + AS_NOMINEE_ANOTHER_ENTITY + ENGLAND_WALES + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_REGOWNER_AS_NOMINEEANOTHERENTITY_SCOTLAND", REGISTERED_OWNER + AS_NOMINEE_ANOTHER_ENTITY + SCOTLAND + REGISTERED_OVERSEAS_ENTITY),
            entry("OE_REGOWNER_AS_NOMINEEANOTHERENTITY_NORTHERNIRELAND", REGISTERED_OWNER + AS_NOMINEE_ANOTHER_ENTITY + NORTHERN_IRELAND + REGISTERED_OVERSEAS_ENTITY)
        );
    }
}
