pscs:
  delta:
    group-id: ${PSC_DELTA_GROUP_ID:psc-delta-consumer}
    topic: ${PSC_DELTA_TOPIC:psc-delta}
    retry-attempts: ${PSC_DELTA_ATTEMPTS:4}
    backoff-delay: ${PSC_DELTA_BACKOFF_DELAY:100}

spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:9092}
    listener:
      concurrency: ${PSC_DELTA_LISTENER_CONCURRENCY:1}

wiremock:
  server:
    port: 8888

api:
  psc-data-api-key: ${PSC_DATA_API_KEY:localhost}
  api-url: ${API_URL:http://localhost:8888}
  internal-api-url: ${INTERNAL_API_URL:localhost}